"""
Django settings for cours project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u65j#0jq1k%02ib*-6b)4i*03ryb3bkvs-8_i2yx5m=$iskj8o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'rest_framework',
    'drf_spectacular',
    'student',
    'nur_comp',
    'teacher',
]



SPECTACULAR_SETTINGS = {

    'TITLE': 'Online Course Management API (NUR_COMP)',  # Аталышты тактоо
    'DESCRIPTION': 'Окуу борборунун маалыматтарын башкаруу үчүн RESTful API: Мугалимдер, Окуучулар, Группалар, Филиалдар, Кызматтар, Отчеттор.',
    'VERSION': '1.0.0',  # Версияны тактоо
    'SERVE_INCLUDE_SCHEMA': False,

    # --- UI жана Функциялык Жөндөөлөр ---
    # Swagger UI'ды ыңгайлуу кылуу үчүн
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,  # URL аркылуу белгилүү бир операцияга өтүү
        'defaultModelsExpandDepth': 1,  # Моделдерди демейки боюнча жабык кармоо
        'defaultModelRendering': 'model',
        'displayRequestDuration': True,  # Сурамдын узактыгын көрсөтүү
        'filter': True,  # Эндпойнтторду издөө үчүн талаа кошуу
    },

    # --- TAGS (ViewSets Топторуна Сүрөттөмө Кошуу) ---
    # Бул сиздин API'ди ар бир ViewSet үчүн бөлүп, сүрөттөп берет
    'TAGS': [
        {'name': 'Teachers', 'description': 'Окутуучулардын тизмесин жана маалыматын башкаруу. (Filter: tag, branch)'},
        {'name': 'Students',
         'description': 'Окуучулардын каттоосун, группасын жана статусун башкаруу. (Filter: group, branch)'},
        {'name': 'Groups', 'description': 'Окуу группалары, алардын графиктери жана статусу жөнүндө маалымат.'},
        {'name': 'Branches', 'description': 'Окуу борборунун бардык филиалдары жөнүндө маалымат.'},
        {'name': 'Services', 'description': 'Окуу кызматтарынын (Төлөмдөр, Абоненттер) маалыматы.'},
        {'name': 'Categories', 'description': 'Мугалимдер же предметтер категорияларын башкаруу.'},
        {'name': 'Subjects', 'description': 'Окутулуучу предметтердин тизмеси.'},
        {'name': 'Analytics', 'description': 'Системалык отчетторду жана статистикалык маалыматтарды башкаруу.'},
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cours.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [

            BASE_DIR / 'cours' / 'templates',
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cours.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'
# !!! Төмөнкү саптарды кошуңуз:
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_ROOT = BASE_DIR / 'staticfiles'


# !!! ОҢДОЛГОН REST_FRAMEWORK БЛОГУ !!!
REST_FRAMEWORK = {
    # Swagger катасын оңдоо үчүн (бул азыр иштеп жатат)

    'DEFAULT_FILTER_BACKENDS': (
        # Фильтрлөө жана Издөө үчүн бул эки сап милдеттүү:
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ),

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    # -----------------------------------------------------
    # !!! URL'ди ОҢДООЧУ НЕГИЗГИ ТАЛААЛАР !!!
    # -----------------------------------------------------

    # URL'дерди салыштырмалуу (relative) кылат:
    'URL_FIELD_NAME': 'url',

    # DRF'ке негизги URL'дерди кайдан баштоону айтат:
    'ROOT_URLCONF': 'cours.urls',

    # Бул дагы көйгөйдү чечиши мүмкүн:
    'SCHEMA_COERCE_PATH_PK': True,

    # -----------------------------------------------------

    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),

    'DEFAULT_PAGINATION_CLASS':
        'rest_framework.pagination.PageNumberPagination',

    'PAGE_SIZE': 20,
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'  # Логин болгондон кийин кайда барат
LOGOUT_REDIRECT_URL = 'login'     # Чыккандан кийин кайсы баракка барат