# Generated by Django 6.0 on 2025-12-19 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nur_comp', '0002_alter_liststudent_gender_alter_listteacher_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема')),
                ('description', models.TextField(verbose_name='Тапшырма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nur_comp.group')),
            ],
            options={
                'verbose_name': 'Үй тапшырма',
                'verbose_name_plural': 'Үй тапшырмалар',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('entry_type', models.CharField(choices=[('presence', 'Келди (+2 балл)'), ('good_job', 'Жакшы тапшырма (+3 балл)'), ('absence', 'Келген жок (-2 балл)')], max_length=20, verbose_name='Түрү')),
                ('points', models.IntegerField(default=0, verbose_name='Балл')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nur_comp.group', verbose_name='Группа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nur_comp.liststudent', verbose_name='Окуучу')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nur_comp.listteacher', verbose_name='Мугалим')),
            ],
            options={
                'verbose_name': 'Журнал жазуусу',
                'verbose_name_plural': 'Журнал',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Дүйшөмбү'), (2, 'Шейшемби'), (3, 'Шаршемби'), (4, 'Бейшемби'), (5, 'Жума'), (6, 'Ишемби'), (7, 'Жекшемби')], verbose_name='Апта күнү')),
                ('start_time', models.TimeField(verbose_name='Башталышы')),
                ('end_time', models.TimeField(verbose_name='Аякташы')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Кабинет')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nur_comp.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nur_comp.listteacher', verbose_name='Мугалим')),
            ],
            options={
                'verbose_name': 'График',
                'verbose_name_plural': 'Графиктер',
            },
        ),
    ]
