# Generated by Django 6.0 on 2025-12-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_homework_id_alter_journal_id_alter_schedule_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Сабак графиги', 'verbose_name_plural': 'Сабактардын графиги'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кабинет'),
        ),
    ]
