# Generated by Django 6.0 on 2025-12-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nur_comp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liststudent',
            name='gender',
            field=models.CharField(choices=[('M', 'Эркек (Мужской)'), ('F', 'Аял (Женский)'), ('O', 'Башка (Другой)')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='listteacher',
            name='gender',
            field=models.CharField(choices=[('M', 'Эркек (Мужской)'), ('F', 'Аял (Женский)'), ('O', 'Башка (Другой)')], default='M', max_length=1),
        ),
    ]
