# Generated by Django 6.0 on 2025-12-22 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nur_comp', '0003_listteacher_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='Аты-жөнү')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон номери')),
                ('parents_phone', models.CharField(blank=True, max_length=20, verbose_name='Ата-энесинин номери')),
                ('address', models.TextField(blank=True, verbose_name='Дареги')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Сүрөтү')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nur_comp.group', verbose_name='Группасы')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Окуучу',
                'verbose_name_plural': 'Окуучулар',
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('entry_type', models.CharField(choices=[('present', 'Келди'), ('absent', 'Жок'), ('late', 'Кечикти')], default='present', max_length=10)),
                ('points', models.IntegerField(default=0, verbose_name='Упай / Баа')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Мугалимдин пикири')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nur_comp.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nur_comp.listteacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='student.studentprofile')),
            ],
            options={
                'verbose_name': 'Баалоо',
                'verbose_name_plural': 'Баалоо журналы',
            },
        ),
    ]
